# Sanity check
## Minimal verification that cascade produces non-nonsense trajectories

In [31]:
%load_ext autoreload
%autoreload 2
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from ase.db import connect

from cascade.agents.db_orm import TrajectoryDB, DBTrajectoryFrame

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [2]:
?TrajectoryDB

Init signature: TrajectoryDB(db_url: 'str', logger: 'Optional[logging.Logger]' = None)
Docstring:      Wrapper for the database representations of trajectories and chunks
Init docstring:
Initialize the trajectory database manager

Args:
    db_url: PostgreSQL connection URL (e.g., 'postgresql://user:pass@host:port/dbname')
    logger: Optional logger for tracking engine creation
File:           ~/repos/cascade/cascade/agents/db_orm.py
Type:           type
Subclasses:

In [3]:
db_url = 'postgresql://ase:pw@localhost:5432/cascade'
db = TrajectoryDB(db_url)
ase_db = connect(db_url)

In [4]:
runs = pd.DataFrame.from_records(db.list_runs())

In [5]:
runs.head()

,run_id,first_created,last_updated,n_trajectories,n_done_trajectories
0,2026.02.26-21:02:15-8cb6ff,2026-02-26 15:02:15.287713-06:00,2026-02-26 15:03:08.573944-06:00,8,1
1,2026.02.26-20:59:39-656747,2026-02-26 14:59:39.209503-06:00,2026-02-26 15:01:20.524063-06:00,8,1
2,2026.02.26-19:50:32-656747,2026-02-26 13:50:32.687985-06:00,2026-02-26 13:50:33.307220-06:00,8,0
3,2026.02.26-19:03:27-656747,2026-02-26 13:03:27.412043-06:00,2026-02-26 13:03:44.051738-06:00,8,0
4,2026.02.26-18:59:29-cbece8,2026-02-26 12:59:29.901189-06:00,2026-02-26 13:00:15.862574-06:00,4,4

In [6]:
runs.tail()

,run_id,first_created,last_updated,n_trajectories,n_done_trajectories
290,2025.10.31-18:21:40-451a69,2025-10-31 13:21:40.509101-05:00,2025-10-31 13:21:40.519187-05:00,2,0
291,2025.10.31-18:18:57-451a69,2025-10-31 13:18:57.625552-05:00,2025-10-31 13:18:57.635521-05:00,2,0
292,2025.10.31-18:18:16-451a69,2025-10-31 13:18:16.936863-05:00,2025-10-31 13:18:16.947114-05:00,2,0
293,2025.10.31-18:17:34-451a69,2025-10-31 13:17:34.834340-05:00,2025-10-31 13:17:34.844208-05:00,2,0
294,2025.10.31-18:17:13-451a69,2025-10-31 13:17:13.515018-05:00,2025-10-31 13:17:13.521163-05:00,2,0

In [7]:
#last_run_id = good_run = '2026.02.26-18:47:48-cbece8'

In [8]:
last_run_id = runs['run_id'][0]
db.list_run_summary(last_run_id)

{'run_id': '2026.02.26-21:02:15-8cb6ff',
 'n_trajectories': 8,
 'n_done': 1,
 'n_active': 7,
 'total_chunks': 13,
 'total_passed_chunks': 6,
 'total_failed_chunks': 3,
 'total_pending_chunks': 4,
 'total_training_frames': 15,
 'first_created': datetime.datetime(2026, 2, 26, 15, 2, 15, 287713, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=64800))),
 'last_updated': datetime.datetime(2026, 2, 26, 15, 3, 8, 573944, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=64800)))}

In [9]:
traj_info = pd.DataFrame.from_records(db.list_trajectories_in_run(last_run_id))
traj_info

,traj_id,target_length,chunks_completed,status,created_at,updated_at
0,0,40,0,TrajectoryStatus.RUNNING,2026-02-26 15:02:15.287713-06:00,2026-02-26 15:02:15.287713-06:00
1,1,40,0,TrajectoryStatus.RUNNING,2026-02-26 15:02:15.404475-06:00,2026-02-26 15:02:15.404475-06:00
2,2,40,0,TrajectoryStatus.RUNNING,2026-02-26 15:02:15.511929-06:00,2026-02-26 15:02:15.511929-06:00
3,3,40,0,TrajectoryStatus.RUNNING,2026-02-26 15:02:15.622354-06:00,2026-02-26 15:02:15.622354-06:00
4,4,40,2,TrajectoryStatus.RUNNING,2026-02-26 15:02:15.729534-06:00,2026-02-26 15:02:51.011838-06:00
5,5,40,4,TrajectoryStatus.COMPLETED,2026-02-26 15:02:15.844885-06:00,2026-02-26 15:03:08.573944-06:00
6,6,40,0,TrajectoryStatus.RUNNING,2026-02-26 15:02:15.988453-06:00,2026-02-26 15:02:15.988453-06:00
7,7,40,0,TrajectoryStatus.RUNNING,2026-02-26 15:02:16.106778-06:00,2026-02-26 15:02:16.106778-06:00

In [10]:
run_summary = db.list_trajectory_summary(last_run_id, 0)
run_summary

{'run_id': '2026.02.26-21:02:15-8cb6ff',
 'traj_id': 0,
 'target_length': 40,
 'chunks_completed': 0,
 'created_at': datetime.datetime(2026, 2, 26, 15, 2, 15, 287713, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=64800))),
 'updated_at': datetime.datetime(2026, 2, 26, 15, 2, 15, 287713, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=64800))),
 'n_chunk_attempts': 1,
 'n_unique_chunks': 1,
 'chunk_breakdown': {0: {'n_attempts': 1,
   'latest_status': 'FAILED',
   'latest_attempt_index': 0}},
 'status_counts': {'PENDING': 0, 'PASSED': 0, 'FAILED': 1}}

In [11]:
chunks = pd.DataFrame.from_records(run_summary['chunk_breakdown'])
chunks

                           0
n_attempts                 1
latest_status         FAILED
latest_attempt_index       0

In [12]:
traj_ids = traj_info['traj_id']

In [13]:
pd.set_option('display.max_rows', 100)

In [14]:
attempt_details = []
for traj_id in traj_ids:
    df = pd.DataFrame.from_records(db.list_trajectory_attempts(last_run_id, 0))
    df.insert(loc=0, column='traj_id', value=traj_id)
    attempt_details.append(df)
attempt_details = pd.concat(attempt_details)
attempt_details

,traj_id,chunk_id,attempt_index,n_frames,audit_status,model_version,created_at,updated_at
0,0,0,0,10,FAILED,0,2026-02-26 15:02:18.133681-06:00,2026-02-26 15:02:34.352987-06:00
0,1,0,0,10,FAILED,0,2026-02-26 15:02:18.133681-06:00,2026-02-26 15:02:34.352987-06:00
0,2,0,0,10,FAILED,0,2026-02-26 15:02:18.133681-06:00,2026-02-26 15:02:34.352987-06:00
0,3,0,0,10,FAILED,0,2026-02-26 15:02:18.133681-06:00,2026-02-26 15:02:34.352987-06:00
0,4,0,0,10,FAILED,0,2026-02-26 15:02:18.133681-06:00,2026-02-26 15:02:34.352987-06:00
0,5,0,0,10,FAILED,0,2026-02-26 15:02:18.133681-06:00,2026-02-26 15:02:34.352987-06:00
0,6,0,0,10,FAILED,0,2026-02-26 15:02:18.133681-06:00,2026-02-26 15:02:34.352987-06:00
0,7,0,0,10,FAILED,0,2026-02-26 15:02:18.133681-06:00,2026-02-26 15:02:34.352987-06:00

### These statuses are getting set at goofy times. the log says that these passed or failed, but theyre pending in the db...

In [15]:
passed_attempts = attempt_details.query('audit_status == "PASSED"')
passed_attempts.shape

(0, 8)

In [16]:
passed_attempts.groupby(['traj_id', 'chunk_id']).size().count()

0

In [23]:
# for traj_id in traj_ids: 
#     traj = db.get_trajectory_atoms(last_run_id, traj_id)
#     r0 = traj[0].get_positions()
#     mad = np.zeros(len(traj))
#     for i, a in enumerate(traj):
#         mad[i] = np.mean(np.abs(a.get_positions() - r0))
#     plt.plot(mad)
#     t = np.arange(mad.shape[0])
#     plt.scatter(t, mad)
#     plt.xlabel('timestep')
#     plt.ylabel('$\mathbf{mean} [|\mathbf{r}_0 - \mathbf{r}_t|]$')
#     plt.title(f'Traj {traj_id}')
#     plt.show()

In [24]:
for traj_id in traj_ids: 
    traj = db.get_trajectory_atoms(last_run_id, traj_id)
    print(f'traj: {traj_id}, n_frames: {len(traj)}')

traj: 0, n_frames: 0
traj: 1, n_frames: 0
traj: 2, n_frames: 0
traj: 3, n_frames: 0
traj: 4, n_frames: 21
traj: 5, n_frames: 41
traj: 6, n_frames: 0
traj: 7, n_frames: 0

This is just using the conveneince method `get_trajectory_atoms`, lets see if anything at all got written by using a direct query.
Notably, `get_trajectory_atoms` will only return atoms from chunks that have passed an audit, so we need a direct query to see if any progress was made

Here is a method we can use:

In [25]:
db.get_latest_chunk_attempt_atoms?

Signature:
db.get_latest_chunk_attempt_atoms(
    run_id: 'str',
    traj_id: 'int',
    chunk_id: 'int',
) -> 'list[Atoms]'
Docstring:
Get the atoms for the latest attempt of a chunk

Args:
    run_id: Run identifier
    traj_id: Trajectory identifier
    chunk_id: Chunk identifier

Returns:
    List of Atoms objects for the latest chunk attempt (empty if none found)
File:      ~/repos/cascade/cascade/agents/db_orm.py
Type:      method

In [ ]:
failed_trajectories = [1,2,3,6]

In [28]:
for traj_id in traj_ids:
    frames = db.get_latest_chunk_attempt_atoms(run_id=last_run_id, 
                                               traj_id=traj_id, 
                                               chunk_id=0)
    print(f'Frames written in chunk 0 for traj {traj_id}: {len(frames)}')

Frames written in chunk 0 for traj 0: 11
Frames written in chunk 0 for traj 1: 0
Frames written in chunk 0 for traj 2: 0
Frames written in chunk 0 for traj 3: 0
Frames written in chunk 0 for traj 4: 11
Frames written in chunk 0 for traj 5: 11
Frames written in chunk 0 for traj 6: 0
Frames written in chunk 0 for traj 7: 11

Okay, so thats a little more evidence for whats going on.

Lets do an even more direct query as a sanity re-check

In [38]:
for traj_id in traj_ids:
    with db.session() as sess:
        frames = sess.query(DBTrajectoryFrame).filter_by(
            run_id=last_run_id,
            traj_id=traj_id,
            chunk_id=0,
            attempt_index=0
        ).order_by(DBTrajectoryFrame.frame_index).all()
    print(f'Frames written in chunk 0 for traj {traj_id}: {len(frames)}')

Frames written in chunk 0 for traj 0: 11
Frames written in chunk 0 for traj 1: 0
Frames written in chunk 0 for traj 2: 0
Frames written in chunk 0 for traj 3: 0
Frames written in chunk 0 for traj 4: 11
Frames written in chunk 0 for traj 5: 11
Frames written in chunk 0 for traj 6: 0
Frames written in chunk 0 for traj 7: 11

Okay, it seems like no frames ever get written. This is useful information.   
Notably, the db is flushed and refreshed after each frame write...

In [18]:
events = db.list_chunk_events(last_run_id)
events = pd.DataFrame.from_records(events)

In [19]:
pd.set_option('display.max_rows', 500)

In [20]:
events.sort_values([
    'traj_id', 
    'chunk_id', 
    'created_at'])

,run_id,traj_id,chunk_id,attempt_index,event_type,frame_id,created_at
0,2026.02.26-21:02:15-8cb6ff,0,0,0,STARTED_DYNAMICS,NaN,2026-02-26 15:02:16.784298-06:00
1,2026.02.26-21:02:15-8cb6ff,0,0,0,FINISHED_DYNAMICS,NaN,2026-02-26 15:02:32.552944-06:00
2,2026.02.26-21:02:15-8cb6ff,0,0,0,STARTED_AUDIT,NaN,2026-02-26 15:02:33.226998-06:00
3,2026.02.26-21:02:15-8cb6ff,0,0,0,AUDIT_FAILED,NaN,2026-02-26 15:02:35.019700-06:00
4,2026.02.26-21:02:15-8cb6ff,0,0,0,STARTED_SAMPLING,NaN,2026-02-26 15:02:38.835349-06:00
5,2026.02.26-21:02:15-8cb6ff,0,0,0,STARTED_LABELING,NaN,2026-02-26 15:02:39.445454-06:00
6,2026.02.26-21:02:15-8cb6ff,0,0,0,STARTED_LABELING_FRAME,12837.0,2026-02-26 15:02:39.909840-06:00
7,2026.02.26-21:02:15-8cb6ff,0,0,0,FINISHED_LABELING_FRAME,12837.0,2026-02-26 15:02:40.773777-06:00
8,2026.02.26-21:02:15-8cb6ff,0,0,0,STARTED_LABELING_FRAME,12816.0,2026-02-26 15:02:41.224660-06:00
9,2026.02.26-21:02:15-8cb6ff,0,0,0,FINISHED_LABELING_FRAME,12816.0,2026-02-26 15:02:41.550273-06:00
10,2026.02.26-21:02:15-8cb6ff,0,0,0,STARTED_LABELING_FRAME,12812.0,2026-02-26 15:02:41.886360-06:00
11,2026.02.26-21:02:15-8cb6ff,0,0,0,FINISHED_LABELING_FRAME,12812.0,2026-02-26 15:02:42.403244-06:00
12,2026.02.26-21:02:15-8cb6ff,0,0,0,STARTED_LABELING_FRAME,12834.0,2026-02-26 15:02:42.775036-06:00
13,2026.02.26-21:02:15-8cb6ff,0,0,0,FINISHED_LABELING_FRAME,12834.0,2026-02-26 15:02:43.121063-06:00
14,2026.02.26-21:02:15-8cb6ff,0,0,0,STARTED_LABELING_FRAME,12830.0,2026-02-26 15:02:43.575577-06:00
15,2026.02.26-21:02:15-8cb6ff,0,0,0,FINISHED_LABELING_FRAME,12830.0,2026-02-26 15:02:44.076444-06:00
16,2026.02.26-21:02:15-8cb6ff,0,0,0,FINISHED_LABELING,NaN,2026-02-26 15:02:44.421643-06:00
17,2026.02.26-21:02:15-8cb6ff,0,0,0,FINISHED_SAMPLING,NaN,2026-02-26 15:02:44.600972-06:00
18,2026.02.26-21:02:15-8cb6ff,1,0,0,STARTED_DYNAMICS,NaN,2026-02-26 15:02:16.314808-06:00
19,2026.02.26-21:02:15-8cb6ff,2,0,0,STARTED_DYNAMICS,NaN,2026-02-26 15:02:16.561662-06:00
20,2026.02.26-21:02:15-8cb6ff,3,0,0,STARTED_DYNAMICS,NaN,2026-02-26 15:02:16.324555-06:00
21,2026.02.26-21:02:15-8cb6ff,4,0,0,STARTED_DYNAMICS,NaN,2026-02-26 15:02:16.894093-06:00
22,2026.02.26-21:02:15-8cb6ff,4,0,0,FINISHED_DYNAMICS,NaN,2026-02-26 15:02:35.020267-06:00
23,2026.02.26-21:02:15-8cb6ff,4,0,0,STARTED_AUDIT,NaN,2026-02-26 15:02:35.879249-06:00
24,2026.02.26-21:02:15-8cb6ff,4,0,0,AUDIT_PASSED,NaN,2026-02-26 15:02:38.960100-06:00
25,2026.02.26-21:02:15-8cb6ff,4,1,0,STARTED_DYNAMICS,NaN,2026-02-26 15:02:39.204480-06:00
26,2026.02.26-21:02:15-8cb6ff,4,1,0,FINISHED_DYNAMICS,NaN,2026-02-26 15:02:50.136713-06:00
27,2026.02.26-21:02:15-8cb6ff,4,1,0,STARTED_AUDIT,NaN,2026-02-26 15:02:50.469256-06:00
28,2026.02.26-21:02:15-8cb6ff,4,1,0,AUDIT_PASSED,NaN,2026-02-26 15:02:51.122579-06:00
29,2026.02.26-21:02:15-8cb6ff,4,2,0,STARTED_DYNAMICS,NaN,2026-02-26 15:02:51.334695-06:00
30,2026.02.26-21:02:15-8cb6ff,4,2,0,FINISHED_DYNAMICS,NaN,2026-02-26 15:02:57.169444-06:00
31,2026.02.26-21:02:15-8cb6ff,4,2,0,STARTED_AUDIT,NaN,2026-02-26 15:02:57.427972-06:00
32,2026.02.26-21:02:15-8cb6ff,4,2,0,AUDIT_FAILED,NaN,2026-02-26 15:02:58.017347-06:00
33,2026.02.26-21:02:15-8cb6ff,4,2,0,STARTED_SAMPLING,NaN,2026-02-26 15:02:58.804094-06:00
34,2026.02.26-21:02:15-8cb6ff,4,2,0,STARTED_LABELING,NaN,2026-02-26 15:02:59.032113-06:00
35,2026.02.26-21:02:15-8cb6ff,4,2,0,STARTED_LABELING_FRAME,12868.0,2026-02-26 15:02:59.255015-06:00
36,2026.02.26-21:02:15-8cb6ff,4,2,0,FINISHED_LABELING_FRAME,12868.0,2026-02-26 15:03:00.017983-06:00
37,2026.02.26-21:02:15-8cb6ff,4,2,0,STARTED_LABELING_FRAME,12872.0,2026-02-26 15:03:00.675072-06:00
38,2026.02.26-21:02:15-8cb6ff,4,2,0,FINISHED_LABELING_FRAME,12872.0,2026-02-26 15:03:01.254318-06:00
39,2026.02.26-21:02:15-8cb6ff,4,2,0,STARTED_LABELING_FRAME,12874.0,2026-02-26 15:03:01.579507-06:00
40,2026.02.26-21:02:15-8cb6ff,4,2,0,FINISHED_LABELING_FRAME,12874.0,2026-02-26 15:03:02.226804-06:00
41,2026.02.26-21:02:15-8cb6ff,4,2,0,STARTED_LABELING_FRAME,12881.0,2026-02-26 15:03:02.555497-06:00
42,2026.02.26-21:02:15-8cb6ff,4,2,0,FINISHED_LABELING_FRAME,12881.0,2026-02-26 15:03:02.892025-06:00
43,2026.02.26-21:02:15-8cb6ff,4,2,0,STARTED_LABELING_FRAME,12877.0,2026-02-26 15:03:03.324041-06:00
44,2026.02.26-21:02:15-8cb6ff,4,2,0,FINISHED_LABELING_FRAME,12877.0,2026-02-26 15:03:03.660756-06:00
45,2026.02.26-21:02:15-8cb6ff,4,2,0,FINISHED_LABELING,NaN,2026-02-26 15:03:03.934192-06:00
46,2026.02.26-21:02:15-8cb6ff,4,2,0,FINISHED_SAMPLING,NaN,2026-02-26 15:03:04.070997-06:00
47,2026.02.26-21:02:15-8cb6ff,5,0,0,STARTED_DYNAMICS,NaN,2026-02-26 15:02:16.891914-06:00
48,2026.02.26-21:02:15-8cb6ff,5,0,0,FINISHED_DYNAMICS,NaN,2026-02-26 15:02:35.407115-06:00
49,2026.02.26-21:02:15-8cb6ff,5,0,0,STARTED_AUDIT,NaN,2026-02-26 15:02:37.264087-06:00
50,2026.02.26-21:02:15-8cb6ff,5,0,0,AUDIT_PASSED,NaN,2026-02-26 15:02:39.563255-06:00
51,2026.02.26-21:02:15-8cb6ff,5,1,0,STARTED_DYNAMICS,NaN,2026-02-26 15:02:39.914750-06:00
52,2026.02.26-21:02:15-8cb6ff,5,1,0,FINISHED_DYNAMICS,NaN,2026-02-26 15:02:48.982861-06:00
53,2026.02.26-21:02:15-8cb6ff,5,1,0,STARTED_AUDIT,NaN,2026-02-26 15:02:49.227687-06:00
54,2026.02.26-21:02:15-8cb6ff,5,1,0,AUDIT_PASSED,NaN,2026-02-26 15:02:49.911121-06:00
55,2026.02.26-21:02:15-8cb6ff,5,2,0,STARTED_DYNAMICS,NaN,2026-02-26 15:02:50.024827-06:00
56,2026.02.26-21:02:15-8cb6ff,5,2,0,FINISHED_DYNAMICS,NaN,2026-02-26 15:02:58.926139-06:00
57,2026.02.26-21:02:15-8cb6ff,5,2,0,STARTED_AUDIT,NaN,2026-02-26 15:02:59.474764-06:00
58,2026.02.26-21:02:15-8cb6ff,5,2,0,AUDIT_PASSED,NaN,2026-02-26 15:03:00.896493-06:00
59,2026.02.26-21:02:15-8cb6ff,5,3,0,STARTED_DYNAMICS,NaN,2026-02-26 15:03:01.113439-06:00
60,2026.02.26-21:02:15-8cb6ff,5,3,0,FINISHED_DYNAMICS,NaN,2026-02-26 15:03:07.862038-06:00
61,2026.02.26-21:02:15-8cb6ff,5,3,0,STARTED_AUDIT,NaN,2026-02-26 15:03:08.103672-06:00
62,2026.02.26-21:02:15-8cb6ff,5,3,0,AUDIT_PASSED,NaN,2026-02-26 15:03:08.696681-06:00
63,2026.02.26-21:02:15-8cb6ff,6,0,0,STARTED_DYNAMICS,NaN,2026-02-26 15:02:16.559115-06:00
64,2026.02.26-21:02:15-8cb6ff,7,0,0,STARTED_DYNAMICS,NaN,2026-02-26 15:02:16.564056-06:00
65,2026.02.26-21:02:15-8cb6ff,7,0,0,FINISHED_DYNAMICS,NaN,2026-02-26 15:02:27.976873-06:00
66,2026.02.26-21:02:15-8cb6ff,7,0,0,STARTED_AUDIT,NaN,2026-02-26 15:02:28.369057-06:00
67,2026.02.26-21:02:15-8cb6ff,7,0,0,AUDIT_FAILED,NaN,2026-02-26 15:02:29.830801-06:00
68,2026.02.26-21:02:15-8cb6ff,7,0,0,STARTED_SAMPLING,NaN,2026-02-26 15:02:30.624661-06:00
69,2026.02.26-21:02:15-8cb6ff,7,0,0,STARTED_LABELING,NaN,2026-02-26 15:02:31.056028-06:00
70,2026.02.26-21:02:15-8cb6ff,7,0,0,STARTED_LABELING_FRAME,12802.0,2026-02-26 15:02:31.170712-06:00
71,2026.02.26-21:02:15-8cb6ff,7,0,0,FINISHED_LABELING_FRAME,12802.0,2026-02-26 15:02:31.531106-06:00
72,2026.02.26-21:02:15-8cb6ff,7,0,0,STARTED_LABELING_FRAME,12797.0,2026-02-26 15:02:31.982022-06:00
73,2026.02.26-21:02:15-8cb6ff,7,0,0,FINISHED_LABELING_FRAME,12797.0,2026-02-26 15:02:32.325828-06:00
74,2026.02.26-21:02:15-8cb6ff,7,0,0,STARTED_LABELING_FRAME,12833.0,2026-02-26 15:02:32.765599-06:00
75,2026.02.26-21:02:15-8cb6ff,7,0,0,FINISHED_LABELING_FRAME,12833.0,2026-02-26 15:02:33.335952-06:00
76,2026.02.26-21:02:15-8cb6ff,7,0,0,STARTED_LABELING_FRAME,12818.0,2026-02-26 15:02:33.897093-06:00
77,2026.02.26-21:02:15-8cb6ff,7,0,0,FINISHED_LABELING_FRAME,12818.0,2026-02-26 15:02:35.020726-06:00
78,2026.02.26-21:02:15-8cb6ff,7,0,0,STARTED_LABELING_FRAME,12814.0,2026-02-26 15:02:36.107374-06:00
79,2026.02.26-21:02:15-8cb6ff,7,0,0,FINISHED_LABELING_FRAME,12814.0,2026-02-26 15:02:36.800751-06:00
80,2026.02.26-21:02:15-8cb6ff,7,0,0,FINISHED_LABELING,NaN,2026-02-26 15:02:37.263421-06:00
81,2026.02.26-21:02:15-8cb6ff,7,0,0,FINISHED_SAMPLING,NaN,2026-02-26 15:02:37.511139-06:00